Repository bandya2003/MLProjectTraining, pull requests merged in 2022-10, with the labels that each got.

#2 Added car images
  New folder/cars dataset.jpg
  New folder/download (1).jpg
  New folder/download (2).jpg
  New folder/download (3).jpg
  New folder/download (4).jpg
  New folder/download (5).jpg
  New folder/download (6).jpg
  New folder/download (7).jpg
  New folder/download (8).jpg
  New folder/download (9).jpg
  New folder/download.jpg
Labels: enhancement, good first issue, hacktoberfest-accepted

#1 Created detection.py for Object Detection
  detection.py
Labels: enhancement, hacktoberfest-accepted

#3 added a sample image used in the model
  opencv-od.png
Labels: documentation, good first issue, hacktoberfest-accepted

#4 Fruits Images
  fruits/apples-1296x728-header.webp
  fruits/artificial-small-grapes-for-kitchen-wall-hanging-decor-parties-original-imafur6ghyayqgkr.webp
  fruits/fruit-salad.webp
  fruits/fruits-in-french-11.jpg
  fruits/healthiest-fruits-lemons.jpg
  fruits/high-protein-fruits-guava.webp
  fruits/images.jpg
  fruits/ordinary-fruits-with-amazing-health-benefits-09-1440x810.jpg
  fruits/pexels-mali-maeder-102104.jpg
  fruits/pexels-pixabay-51312.jpg
  fruits/photo-1601004890684-d8cbf643f5f2.jpg
Labels: enhancement, help wanted, hacktoberfest-accepted

#5 Flowers Dataset Images
  flowers/The-Rose-Queen-of-the-Flowers-and-Symbol-of-Love-702x527.jpg
  flowers/aster-flowers-art-design-26968847.jpg
  flowers/copy-space-roses-flowers_23-2148860032.jpg
  flowers/dahlia-red-blossom-bloom-60597.jpeg
  flowers/flowers-4929984 (1).jpg
  flowers/flowers-4929984.jpg
  flowers/head-treasure-flower-disk-flowers-inflorescence-ray.webp
  flowers/helianthus-yellow-flower-pixabay_11863.webp
  flowers/lotus-flower-in-pond-732x549-thumbnail-732x549.jpg
  flowers/marguerite-729510__340.webp
  flowers/pexels-jonas-kakaroto-736230.jpg
  flowers/photo-1600703136783-bdb5ea365239.jpg
Labels: enhancement, good first issue, hacktoberfest-accepted

#8 add new python project
  Attempt 1.py
Labels: enhancement, hacktoberfest-accepted

#14 Added Find S algorithm
  ML_algo/FindS_algo.ipynb
Labels: enhancement, hacktoberfest-accepted

#15 diabetestracking.py
  diabetestracking.py
Labels: enhancement, hacktoberfest-accepted

#17 added tiger images
  New folder (2)/animals-wildlife-shutterstock_1066200380.jpg
  New folder (2)/images (1).jfif
  New folder (2)/images (2).jfif
  New folder (2)/images (3).jfif
  New folder (2)/images (4).jfif
  New folder (2)/images (5).jfif
  New folder (2)/images (6).jfif
  New folder (2)/images (7).jfif
  New folder (2)/images (8).jfif
  New folder (2)/images (9).jfif
  New folder (2)/images.jfif
Labels: enhancement, hacktoberfest-accepted

#18 anime
  anime/images (1).jfif
  anime/images (2).jfif
  anime/images (3).jfif
  anime/images (4).jfif
  anime/images (5).jfif
  anime/images (6).jfif
  anime/images (7).jfif
  anime/images (8).jfif
  anime/images (9).jfif
  anime/images.jfif
Labels: enhancement, hacktoberfest-accepted

#19 Added images for data set.
  butterfly/b.jpg
  butterfly/th (1).jpg
  butterfly/th (2).jpg
  butterfly/th (3).jpg
  butterfly/th (4).jpg
  butterfly/th (5).jpg
  butterfly/th (6).jpg
  butterfly/th (7).jpg
  butterfly/th (8).jpg
  butterfly/th.jpg
Labels: enhancement, hacktoberfest-accepted

#20 keyboard
  keyboard/download (1).jfif
  keyboard/download (2).jfif
  keyboard/download (3).jfif
  keyboard/download.jfif
  keyboard/images (1).jfif
  keyboard/images (2).jfif
  keyboard/images (3).jfif
  keyboard/images (4).jfif
  keyboard/images (5).jfif
  keyboard/images.jfif
Labels: enhancement, hacktoberfest-accepted

#21 cat
  cat/download (1).jfif
  cat/download (2).jfif
  cat/download.jfif
  cat/images (1).jfif
  cat/images (2).jfif
  cat/images (3).jfif
  cat/images (4).jfif
  cat/images (5).jfif
  cat/images (6).jfif
  cat/images.jfif
Labels: enhancement, hacktoberfest-accepted

#22 Added data set on BodyBuilders.
  BodyBuilders/th (1).jpg
  BodyBuilders/th (2).jpg
  BodyBuilders/th (3).jpg
  BodyBuilders/th (4).jpg
  BodyBuilders/th (5).jpg
  BodyBuilders/th (6).jpg
  BodyBuilders/th (7).jpg
  BodyBuilders/th (8).jpg
  BodyBuilders/th (9).jpg
  BodyBuilders/th.jpg
Labels: enhancement, hacktoberfest-accepted

#23 Added cow images for your Dataset.
  Cow images/IMG_20220926_163844.jpg
  Cow images/th (1).jpg
  Cow images/th (2).jpg
  Cow images/th (3).jpg
  Cow images/th (4).jpg
  Cow images/th (5).jpg
  Cow images/th (6).jpg
  Cow images/th (7).jpg
  Cow images/th (8).jpg
  Cow images/th.jpg
Labels: enhancement, hacktoberfest-accepted

#24 Added data dets.
  Gaming Laptops/th (1).jpg
  Gaming Laptops/th (2).jpg
  Gaming Laptops/th (3).jpg
  Gaming Laptops/th (4).jpg
  Gaming Laptops/th (5).jpg
  Gaming Laptops/th (6).jpg
  Gaming Laptops/th (7).jpg
  Gaming Laptops/th (8).jpg
  Gaming Laptops/th (9).jpg
  Gaming Laptops/th.jpg
Labels: enhancement, hacktoberfest-accepted

#26 Added this files
  ML_algo/DECISION TREE.ipynb
  ML_algo/candidate.ipynb
Labels: enhancement, hacktoberfest-accepted

#27 [ImgBot] Optimize images
  fruits/fruit-4421752_1920.jpg
  fruits/grapes-1283162_1920.jpg
  fruits/grapes-2032838_1920.jpg
  fruits/grapes-2664482_1920.jpg
  fruits/grapes-3550733_1920.jpg
  fruits/grapes-3555214_1920.jpg
  fruits/grapes-553462_1920.jpg
  fruits/grapes-5889697_1920.jpg
  fruits/riesling-1567409_1920.jpg
Labels: enhancement, hacktoberfest-accepted

#28 Added TicTacToe and Water Jug
  AI/TicTacToe.ipynb
  AI/Water_Jug.ipynb
Labels: enhancement, hacktoberfest-accepted

#29 Create Movie_Recommendation.ibpy
  AI/Movie_Recommendation.ibpy
Labels: enhancement, hacktoberfest-accepted

#30 Create codegeneration.py
  Ml Codes/codegeneration.py
Labels: enhancement, good first issue, hacktoberfest-accepted

#31 Create modelartifacts.py
  Ml Codes/modelartifacts.py
Labels: enhancement, good first issue, hacktoberfest-accepted

#32 Create script.py
  Ml Codes/script.py
Labels: enhancement, hacktoberfest-accepted

#33 Create preparationcode.py
  Ml Codes/preparationcode.py
Labels: enhancement, good first issue, hacktoberfest-accepted

#34 Create featurizationcode.py
  Ml Codes/featurizationcode.py
Labels: documentation, enhancement, hacktoberfest-accepted

#36 Uploaded the different faces of people
  Peple faces/000632.jpg
  Peple faces/001290.jpg
  Peple faces/004465.jpg
  Peple faces/007113.jpg
  Peple faces/011116.jpg
  Peple faces/011121.jpg
  Peple faces/011125.jpg
  Peple faces/011141.jpg
  Peple faces/011149.jpg
  Peple faces/011190.jpg
  Peple faces/032439.jpg
  Peple faces/032534.jpg
  Peple faces/1.jpg
  Peple faces/111331.jpg
  Peple faces/111332.jpg
  Peple faces/111333.jpg
  Peple faces/111334.jpg
  Peple faces/111335.jpg
  Peple faces/111336.jpg
  Peple faces/111337.jpg
  Peple faces/111338.jpg
  Peple faces/111339.jpg
Labels: documentation, enhancement, hacktoberfest-accepted

#35 Create hyperparametersspecification code.py
  Ml Codes/End to end training code.py
  Ml Codes/hyperparametersspecification code.py
Labels: documentation, enhancement, hacktoberfest-accepted

#38 Create model in-memory.py
  Ml Codes/model in-memory.py
Labels: enhancement, hacktoberfest-accepted

#39 added ecommerce images
  ecommerce-images/E-commerce-Website-Development-Services.jpeg
  ecommerce-images/images.jpeg
  ecommerce-images/maxresdefault.jpeg
Labels: enhancement, good first issue, hacktoberfest-accepted

#40 dataset images for bikes by suraj
  .DS_Store
  bikes /.DS_Store
  bikes /download-1.jpg
  bikes /download-2.jpg
  bikes /download-3.jpg
  bikes /download-4.jpg
  bikes /download-5.jpg
  bikes /download-6.jpg
  bikes /download-7.jpg
  bikes /download-8.jpg
  bikes /download-9.jpg
  bikes /download.jpg
Labels: enhancement, hacktoberfest-accepted

#41 Added Dog Images
  Dog Images/dog(1).jpg
  Dog Images/dog(10).jpg
  Dog Images/dog(2).jpg
  Dog Images/dog(3).jpg
  Dog Images/dog(4).jpg
  Dog Images/dog(5).jpg
  Dog Images/dog(6).jpg
  Dog Images/dog(7).jpg
  Dog Images/dog(8).jpg
  Dog Images/dog(9).jpg
Labels: enhancement, hacktoberfest-accepted

#42 dataset of cars by suraj
  .DS_Store
  cars/download-1.jpg
  cars/download-2.jpg
  cars/download-3.jpg
  cars/download-4.jpg
  cars/download-5.jpg
  cars/download-6.jpg
  cars/download-7.jpg
  cars/download-8.jpg
  cars/download-9.jpg
  cars/download.jpg
Labels: duplicate, hacktoberfest-accepted

#43 added panda images
  panda images/panda1.jpg
  panda images/panda10.jpg
  panda images/panda2.jpg
  panda images/panda3.jpg
  panda images/panda4.jpg
  panda images/panda5.jpg
  panda images/panda6.jpg
  panda images/panda7.jpg
  panda images/panda8.jpg
  panda images/panda9.jpg
Labels: enhancement, hacktoberfest-accepted

#45 4th dataset by suraj
  .DS_Store
  pen/download-1.jpg
  pen/download-2.jpg
  pen/download-3.jpg
  pen/download.jpg
  pen/download.png
  pen/images-1.jpg
  pen/images-1.png
  pen/images-2.jpg
  pen/images.jpg
  pen/images.png
Labels: enhancement, hacktoberfest-accepted

#47 Fan Images
  fans/fan1.jpg
  fans/fan10.jpg
  fans/fan11.png
  fans/fan12.jpg
  fans/fan2.png
  fans/fan3.jpg
  fans/fan4.jpg
  fans/fan5.webp
  fans/fan6.jpg
  fans/fan7.jpg
  fans/fan8.jpg
  fans/fan9.jpg
Labels: enhancement, hacktoberfest-accepted

#48 Chair Images
  Chairs/chair1.jpg
  Chairs/chair10.webp
  Chairs/chair11.jpg
  Chairs/chair12.webp
  Chairs/chair2.jpg
  Chairs/chair3.jpg
  Chairs/chair4.jpeg
  Chairs/chair5.webp
  Chairs/chair6.jpeg
  Chairs/chair7.jpeg
  Chairs/chair8.jpg
  Chairs/chair9.webp
Labels: hacktoberfest-accepted

#49 Added 10 trains images
  .DS_Store
  ML_ALgorithms/.DS_Store
  Trains/train.jpeg
  Trains/train2.jpeg
  Trains/train3.jpeg
  Trains/train4.jpeg
  Trains/train5.jpeg
  Trains/train6.jpeg
  Trains/train7.jpeg
  Trains/train8.jpeg
  Trains/train9.jpeg
Labels: enhancement, hacktoberfest-accepted

#50 Added buffalo images
  buffalo/buffalo-1.jpg
  buffalo/buffalo-10.jpg
  buffalo/buffalo-11.jpg
  buffalo/buffalo-2.jpg
  buffalo/buffalo-3.jpg
  buffalo/buffalo-4.jpg
  buffalo/buffalo-5.jpg
  buffalo/buffalo-6.jpg
  buffalo/buffalo-8.jpg
  buffalo/buffalo-9.jpg
Labels: enhancement, hacktoberfest-accepted

#54 Added 10 photos of Trees
  Trees/fall-autumn-red-season.jpeg
  Trees/pexels-photo-1005417.jpeg
  Trees/pexels-photo-1423600.jpeg
  Trees/pexels-photo-1632790.jpeg
  Trees/pexels-photo-1770809.jpeg
  Trees/pexels-photo-1903900.jpeg
  Trees/pexels-photo-288474.jpeg
  Trees/pexels-photo-599708.jpeg
  Trees/pexels-photo-802127.jpeg
  Trees/pexels-photo-962312.jpeg
Labels: enhancement, hacktoberfest-accepted

#53 Added 10 photos of shoes.
  .DS_Store
  Shoes/.DS_Store
  Shoes/shoes.jpeg
  Shoes/shoes1.jpeg
  Shoes/shoes2.jpeg
  Shoes/shoes3.jpeg
  Shoes/shoes4.jpeg
  Shoes/shoes5.jpeg
  Shoes/shoes6.jpeg
  Shoes/shoes7.jpeg
  Shoes/shoes8.jpeg
  Shoes/shoes9.jpeg
Labels: enhancement, hacktoberfest-accepted

#52 added parrot images
  parrot images/Parrot-4.jpg
  parrot images/parrot-1.jpg
  parrot images/parrot-10.jpg
  parrot images/parrot-11.jpg
  parrot images/parrot-12.jpg
  parrot images/parrot-2.jpg
  parrot images/parrot-3.jpg
  parrot images/parrot-5.jpg
  parrot images/parrot-6.jpg
  parrot images/parrot-7.jpg
  parrot images/parrot-8.jpg
  parrot images/parrot-9.jpg
Labels: good first issue, hacktoberfest-accepted

#55 Added Photos of different bags.
  Bags/Bags.jpeg
  Bags/Bags10.jpeg
  Bags/Bags2.jpeg
  Bags/Bags3.jpeg
  Bags/Bags4.jpeg
  Bags/Bags5.jpeg
  Bags/Bags6.jpeg
  Bags/Bags7.jpeg
  Bags/Bags8.jpeg
  Bags/Bags9.jpeg
Labels: enhancement, hacktoberfest-accepted

#56 Dataset of cricket by Aditya Khare
  Cricketer/download (1).jfif
  Cricketer/download (3).jfif
  Cricketer/download (4).jfif
  Cricketer/download (5).jfif
  Cricketer/download (6).jfif
  Cricketer/download (7).jfif
  Cricketer/download.jfif
  Cricketer/images (1).jfif
  Cricketer/images (2).jfif
  Cricketer/images.jfif
  Cricketer/index.html
Labels: enhancement, hacktoberfest-accepted

#61 Added web scapping code in machine learning
  Web Scrapping in ML/Sample_output.csv
  Web Scrapping in ML/Scrapper.py
Labels: enhancement, hacktoberfest-accepted

#57 Dress img
  dress/223715072022-Teal-Silk-Indo-Western-Suit.jpg
  dress/45983e21c8a24a6af165d9fb3b3283f1.jpg
  dress/71U0Wo-rizL._UY550_.jpg
  dress/How-to-dress-well.jpg
  dress/b9209e2c03ef7da44b088e0791ffd011.jpg
  dress/dcd40d9a7f9cf6a52e6cd4b2b93b15f6.jpg
  dress/images (1).jpg
  dress/images.jpg
  dress/main-qimg-d9ab6150e88b8a19eb4c503840491182-lq.jpg
  dress/product-500x500.jpeg
Labels: enhancement, hacktoberfest-accepted

#60 Dataset of cold drink by Aditya Khare
  cold drink/download (1).jfif
  cold drink/download (2).jfif
  cold drink/download (3).jfif
  cold drink/download.jfif
  cold drink/images (1).jfif
  cold drink/images (2).jfif
  cold drink/images (3).jfif
  cold drink/images (4).jfif
  cold drink/images (5).jfif
  cold drink/images.jfif
  cold drink/index.html
Labels: good first issue, hacktoberfest-accepted

#58 Dataset of ipl teams by Aditya Khare
  teams/download (1).jfif
  teams/download (2).jfif
  teams/download (3).jfif
  teams/download.jfif
  teams/download.png
  teams/images (1).jfif
  teams/images (1).png
  teams/images (2).jfif
  teams/images.jfif
  teams/images.png
  teams/index.html
Labels: enhancement, hacktoberfest-accepted

#63 cartoon
  cartoon/index.html
  download (1).jpg
  download (1).png
  download (2).jpg
  download (2).png
  download (9).jpg
  download.jpg
  download.png
  images (1).jpg
  images.jpg
  images.png
Labels: enhancement, hacktoberfest-accepted

#67 added one file to anime folder
  Bags/bag_image1.jpg
  Dog Images/group-portrait-adorable-puppies_53876-64778.webp
  Trains/train1.jpg
  anime/wp1809658-anime-4k-wallpapers.jpg
Labels: enhancement, hacktoberfest-accepted

#69 added chair image
  Chairs/chair_image_12.jpg
Labels: enhancement, hacktoberfest-accepted

#70 added tree image 1
  Trees/tree_image_1.jpg
Labels: enhancement, hacktoberfest-accepted

#72 optimize images
  mahendra-singh-dhoni-5835730_1280.png
  man-5719960_1280.png
  man-5719988_1280.png
  mukesh-ambani-5747977_1280.png
  ratan-tata-5747953_1280.png
  sachin-tendulkar-5835753_1280.png
  salman-khan-5747949_1280.png
  shahrukh-khan-5747951_1280.png
  virat-kohli-5835744_1280.png
Labels: enhancement, hacktoberfest-accepted

#71 added 10 dog images
  Dog Images/dog(10).jpg
  Dog Images/dog(11).jpg
  Dog Images/dog(12).jpg
  Dog Images/dog(13).jpg
  Dog Images/dog(14).jpg
  Dog Images/dog(15).jpg
  Dog Images/dog(16).jpg
  Dog Images/dog(17).jpg
  Dog Images/dog(18).jpg
  Dog Images/dog(19).jpg
  Dog Images/dog(20).jpg
Labels: enhancement, hacktoberfest-accepted

#85 human count detector
  human count detector
Labels: enhancement, hacktoberfest-accepted

#82 birds by Aashu singh
  bird/download (1).jpg
  bird/download (2).jpg
  bird/download (3).jpg
  bird/download (4).jpg
  bird/download (5).jpg
  bird/download.jpg
  bird/images (1).jpg
  bird/images (2).jpg
  bird/images (3).jpg
  bird/images.jpg
  bird/index.html
Labels: hacktoberfest-accepted

#91 Delete 111331.jpg
  Peple faces/111331.jpg
Labels: enhancement, hacktoberfest-accepted

#90 Update ProjectSettings.json
  .vs/ProjectSettings.json
Labels: good first issue, hacktoberfest-accepted

#89 Update human count detector
  human count detector
Labels: enhancement, hacktoberfest-accepted

#88 Update detection.py
  detection.py
Labels: enhancement, hacktoberfest-accepted

#92 add manggo image into fruit dataset
  bikes/.DS_Store
  bikes/download-1.jpg
  bikes/download-2.jpg
  bikes/download-3.jpg
  bikes/download-4.jpg
  bikes/download-5.jpg
  bikes/download-6.jpg
  bikes/download-7.jpg
  bikes/download-8.jpg
  bikes/download-9.jpg
  bikes/download.jpg
  fruits/mangoo/Fresh Mango Fruit Isolated White.jpg
  fruits/mangoo/Fruit photography_ Fruits photos.jpg
  fruits/mangoo/Mango - Wikipedia.jpg
  fruits/mangoo/Mango Large - Albertsons.webp
  fruits/mangoo/One Mango Fruit - Free Transparent PNG.png
  fruits/mangoo/One Mango yellow color food fruit.jpg
  fruits/mangoo/One ripe yellow mango with a green leaf.jpg
  fruits/mangoo/One whole yellow mango fruit isolated.jpg
  fruits/mangoo/Organic Ripe Yellow Mango Tropical.jpg
  fruits/mangoo/Single Tropical Mango Fruit Isolated On.webp
  fruits/mangoo/Watermelon smoothies_ Mango fruit.png
  fruits/mangoo/Yellow mango fruit illustration_ Mango.png
  fruits/mangoo/the Alphonso Mango_ Deemed.jpg
Labels: enhancement, hacktoberfest-accepted

#94 Added pen image
  pen/download (5).jpg
Labels: enhancement, hacktoberfest-accepted

#96 Added chair image
  Chairs/download (6).jpg
Labels: enhancement, hacktoberfest-accepted

#97 Add files via upload
  Bags/download (1).jpg
  Bags/download (2).jpg
  Bags/download (3).jpg
  Bags/download (4).jpg
  Bags/download (5).jpg
  Bags/download (6).jpg
  Bags/download (7).jpg
  Bags/images (1).jpg
  Bags/images (2).jpg
  Bags/images.jpg
Labels: enhancement, hacktoberfest-accepted

#98 Add files via upload
  Chairs/download (1).jpg
  Chairs/download (10).jpg
  Chairs/download (2).jpg
  Chairs/download (3).jpg
  Chairs/download (4).jpg
  Chairs/download (5).jpg
  Chairs/download (6).jpg
  Chairs/download (7).jpg
  Chairs/download (8).jpg
  Chairs/download (9).jpg
Labels: enhancement, hacktoberfest-accepted

#99 Add files via upload
  Cow images/download (1).jpg
  Cow images/download (10).jpg
  Cow images/download (2).jpg
  Cow images/download (3).jpg
  Cow images/download (4).jpg
  Cow images/download (5).jpg
  Cow images/download (6).jpg
  Cow images/download (7).jpg
  Cow images/download (8).jpg
  Cow images/download (9).jpg
  Cricketer/download (1).jpg
  Cricketer/download (10).jpg
  Cricketer/download (2).jpg
  Cricketer/download (3).jpg
  Cricketer/download (4).jpg
  Cricketer/download (5).jpg
  Cricketer/download (6).jpg
  Cricketer/download (7).jpg
  Cricketer/download (8).jpg
  Cricketer/download (9).jpg
Labels: enhancement, hacktoberfest-accepted

#100 Add files via upload
  Gaming Laptops/download (1).jpg
  Gaming Laptops/download (2).jpg
  Gaming Laptops/download (3).jpg
  Gaming Laptops/download (4).jpg
  Gaming Laptops/download (5).jpg
  Gaming Laptops/download (6).jpg
  Gaming Laptops/images (1).jpg
  Gaming Laptops/images (2).jpg
  Gaming Laptops/images (3).jpg
  Gaming Laptops/images.jpg
Labels: enhancement, hacktoberfest-accepted

#101 optimizing images
  australia-1296727_1280.png
  australia-28586_1280.png
  indian-flag-1079098_1920.jpg
  japan-162328_1280.png
  pakistan-162383_1280.png
  russia-26896_1280.png
  south-africa-162425_1280.png
  tunisia-162444_1280.png
  ukraine-162450_1280.png
  usa-flag-830720_1920.jpg
Labels: enhancement, hacktoberfest-accepted

#105 Dataset of Musical instruments
  music instruments dataset/1.jpg
  music instruments dataset/2.jpg
  music instruments dataset/3.jpg
  music instruments dataset/4.jpg
  music instruments dataset/5.jpg
  music instruments dataset/6.jpg
  music instruments dataset/7.jpg
Labels: enhancement, hacktoberfest-accepted

#106 Dataset for Sports equipments
  sports equip dataset/4.jpg
  sports equip dataset/a.jpg
  sports equip dataset/d.jpg
  sports equip dataset/f.jpg
  sports equip dataset/g.jpg
  sports equip dataset/h.jpg
  sports equip dataset/s.jpg
Labels: enhancement, hacktoberfest-accepted

#108 Dataset for clocks
  Clock dataset/1.jpg
  Clock dataset/2.jpg
  Clock dataset/3.jpg
  Clock dataset/4.jpg
  Clock dataset/5.jpg
  Clock dataset/6.jpg
  Clock dataset/7.jpg
Labels: enhancement, hacktoberfest-accepted

#109 Update README.md
  README.md
Labels: enhancement, hacktoberfest-accepted

#110 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: enhancement, hacktoberfest-accepted

#111 Update ProjectSettings.json
  .vs/ProjectSettings.json
Labels: enhancement, hacktoberfest-accepted

#112 Update .gitignore
  Project/Soil Type Detection/.gitignore
Labels: enhancement, hacktoberfest-accepted

#114 Add files for more trainings in anime part
  Entertainments/anime/0e0021df-b9d7-4f39-872a-57f47e8933b2.jpg
  Entertainments/anime/0e3a5f82b8be90e50c34ab73d8501e12ec9df105.png
Labels: enhancement, hacktoberfest-accepted

#115 more anime for training
  Entertainments/anime/01.jpg
  Entertainments/anime/0gq6bu9vgzm81.png
  Entertainments/anime/0gt3qo6vgzm81.jpg
  Entertainments/anime/0hRbYE6WRAnyLu5fhnhD1HEzzaESV2oIEItFo5j4.jpeg
Labels: enhancement, hacktoberfest-accepted

#116 even more anime for training
  Entertainments/anime/1def50db14638448f3c69a748d379160.jpg
  Entertainments/anime/1e07be51a8cac512.jpeg
  Entertainments/anime/1e18d509c3374fd0.jpg
  Entertainments/anime/1f8115b7495f36300559d6baa66418c8b91b434a.png
Labels: enhancement, hacktoberfest-accepted

#118 Added Lychee Dataset
  fruits/Lychee/132_100.jpg
  fruits/Lychee/171_100.jpg
  fruits/Lychee/240_100.jpg
  fruits/Lychee/282_100.jpg
  fruits/Lychee/28_100.jpg
  fruits/Lychee/302_100.jpg
  fruits/Lychee/91_100.jpg
  fruits/Lychee/r_0_100.jpg
  fruits/Lychee/r_108_100.jpg
  fruits/Lychee/r_120_100.jpg
  fruits/Lychee/r_168_100.jpg
  fruits/Lychee/r_205_100.jpg
  fruits/Lychee/r_223_100.jpg
  fruits/Lychee/r_256_100.jpg
  fruits/Lychee/r_257_100.jpg
  fruits/Lychee/r_72_100.jpg
Labels: enhancement, hacktoberfest-accepted

#120 Added Watermelon dataset
  fruits/Watermelon/191_100.jpg
  fruits/Watermelon/303_100.jpg
  fruits/Watermelon/3_100.jpg
  fruits/Watermelon/44_100.jpg
  fruits/Watermelon/74_100.jpg
  fruits/Watermelon/92_100.jpg
  fruits/Watermelon/r_0_100.jpg
  fruits/Watermelon/r_122_100.jpg
  fruits/Watermelon/r_160_100.jpg
  fruits/Watermelon/r_179_100.jpg
  fruits/Watermelon/r_197_100.jpg
  fruits/Watermelon/r_220_100.jpg
  fruits/Watermelon/r_244_100.jpg
  fruits/Watermelon/r_266_100.jpg
  fruits/Watermelon/r_279_100.jpg
  fruits/Watermelon/r_292_100.jpg
  fruits/Watermelon/r_315_100.jpg
  fruits/Watermelon/r_46_100.jpg
Labels: enhancement, hacktoberfest-accepted

#122 adding turn left and turn right data into road sign
  RoadSigns/Turn Left/Abstract Hand Draw Image & Photo (Free.jpg
  RoadSigns/Turn Left/Background. Isolate. Stock Photo.webp
  RoadSigns/Turn Left/Clipart Transparent Background.png
  RoadSigns/Turn Left/Left turn ahead route road sign_ yellow.jpg
  RoadSigns/Turn Left/Right Turn Arrow Reflective Graphic.jpg
  RoadSigns/Turn Left/Sharp left arrow road sign hi-res stock.jpg
  RoadSigns/Turn Left/Signs.png
  RoadSigns/Turn Left/Turn Left Traffic Road Sign isolated on.jpg
  RoadSigns/Turn Left/Turn Left Yellow Traffic Sign Stock.jpg
  RoadSigns/Turn Left/Turn Left png images _ PNGWing.png
  RoadSigns/Turn Left/Turn Left signs _ Social Distancing.gif
  RoadSigns/Turn Left/Turn left - Free arrows icons.png
  RoadSigns/Turn Left/Yellow road sign_ arrow_ turn to the.jpg
  RoadSigns/Turn Right/Abstract Hand Draw Doodle Turn Right.jpg
  RoadSigns/Turn Right/Grunge Yellow Turn Right Arrow Traffic.webp
  RoadSigns/Turn Right/Left Turn Arrow Reflective Graphic Road.jpg
  RoadSigns/Turn Right/Traffic Road Sign Right Turn Arrow.jpg
  RoadSigns/Turn Right/Turn right arrow png images _ PNGWing.png
  RoadSigns/Turn Right/Turn right png images _ PNGEgg.png
  RoadSigns/Turn Right/Yellow Right Turn Road Sign Stock Photo (1).jpg
  RoadSigns/Turn Right/Yellow Right Turn Road Sign Stock Photo.jpg
  RoadSigns/Turn Right/Yellow Road Sign Arrow Turn Left Stock.jpg
  RoadSigns/Turn Right/isolated roadside traffic signage.jpg
  RoadSigns/Turn Right/yellow sign with arrow pointing right.gif
Labels: enhancement, hacktoberfest-accepted

#123 Create no-parking.md
  RoadSigns/No Parking/no-parking.md
Labels: enhancement, hacktoberfest-accepted

#125 added maximum sign of roads
  RoadSigns/sign on roads/Traffic-signs-included-in-the-study.png
  RoadSigns/sign on roads/download.jpg
  RoadSigns/sign on roads/download.png
  RoadSigns/sign on roads/mandatory-traffic-signs.jpg
Labels: enhancement, hacktoberfest-accepted

#124 Apple photos to train dataset
  JDM cars/download (1).jfif
  JDM cars/download (2).jfif
  JDM cars/download (3).jfif
  JDM cars/download (4).jfif
  JDM cars/download (5).jfif
  JDM cars/download (6).jfif
  JDM cars/download (7).jfif
  JDM cars/download.jfif
  JDM cars/images (1).jfif
  JDM cars/images.jfif
  apple/download (1).jfif
  apple/download (2).jfif
  apple/download (3).jfif
  apple/download (8).jfif
  apple/download.jfif
  apple/images (1).jfif
  apple/images (2).jfif
  apple/images (3).jfif
  apple/images (4).jfif
  apple/images.jfif
  mobiles/download (1).jfif
  mobiles/download (2).jfif
  mobiles/download (3).jfif
  mobiles/download (4).jfif
  mobiles/download.jfif
  mobiles/images (1).jfif
  mobiles/images (2).jfif
  mobiles/images (3).jfif
  mobiles/images (4).jfif
  mobiles/images.jfif
Labels: enhancement, hacktoberfest-accepted

#126 Added Images for dataset
  fruits/strawberry/strawberry.jpg
  fruits/strawberry/strawberry1.jpg
  fruits/strawberry/strawberry2.jpg
  fruits/strawberry/strawberry3.jpg
Labels: enhancement, hacktoberfest-accepted

#127 Dataset for Laptops of different brands
  laptops dataset/download (1).jfif
  laptops dataset/download (4).jfif
  laptops dataset/download.jfif
  laptops dataset/images (1).jfif
  laptops dataset/images (2).jfif
  laptops dataset/images (3).jfif
  laptops dataset/images (4).jfif
  laptops dataset/images (5).jfif
  laptops dataset/images (6).jfif
  laptops dataset/images (7).jfif
  laptops dataset/images (8).jfif
  laptops dataset/images.jfif
  laptops/download (1).jfif
  laptops/download (4).jfif
  laptops/download.jfif
  laptops/images (1).jfif
  laptops/images (2).jfif
  laptops/images (3).jfif
  laptops/images (4).jfif
  laptops/images (5).jfif
  laptops/images (6).jfif
  laptops/images (7).jfif
  laptops/images (8).jfif
  laptops/images.jfif
Labels: enhancement, hacktoberfest-accepted

#128 Moto GP
  Motogp/1200-L-gp-de-catalogne-de-motogp-la-grille-de-dpart.jpg
  Motogp/20220917110645_MotoGP_India.jpg
  Motogp/Marc-Marquez-sobre-la-RC213V-en-pista-1280x600.jpg
  Motogp/MotoGP.jpg
  Motogp/Moto_GP.avif
  Motogp/VS47OLHPPBNHZDFEWLD5FIFSG4.jpg
  Motogp/alex-rins-team-suzuki-motogp-1.jpg
  Motogp/download.jpg
  Motogp/fabio-quartararo-yamaha-factor.jpg
  Motogp/motogp-australian-gp-2022-alei-3.jpg
Labels: enhancement, hacktoberfest-accepted

#130 bags Images
  Bags Images/arno-senoner-ZT16YkAYueo-unsplash.jpg
  Bags Images/aurelia-dubois-xzrJCS4grC4-unsplash.jpg
  Bags Images/creative-headline-APNnyM36puU-unsplash.jpg
  Bags Images/diana-light-nvQemFKRBUo-unsplash.jpg
  Bags Images/he-s-her-lobster-9b6UhV4nLZs-unsplash.jpg
  Bags Images/irene-kredenets-jKoRZkv2o0U-unsplash.jpg
  Bags Images/irene-kredenets-pSVYyO-XlJk-unsplash.jpg
  Bags Images/james-ree-ZmeFtu11Hpc-unsplash.jpg
  Bags Images/kelly-sikkema-1Pgq9ZpIatI-unsplash.jpg
  Bags Images/readme.md
  Bags Images/sun-lingyan-_H0fjILH5Vw-unsplash.jpg
  Bags Images/wiser-by-the-mile-SwWCo1k92M4-unsplash.jpg
Labels: enhancement, hacktoberfest-accepted

#131 penguins images added
  Animals/Penguin/Adelie Penguin, Jenny Island, Antarctica.jpeg
  Animals/Penguin/penguins(1).jpeg
  Animals/Penguin/penguins(10).jpeg
  Animals/Penguin/penguins(2).jpeg
  Animals/Penguin/penguins(3).jpeg
  Animals/Penguin/penguins(4).jpeg
  Animals/Penguin/penguins(5).jpeg
  Animals/Penguin/penguins(6).jpeg
  Animals/Penguin/penguins(7).jpeg
  Animals/Penguin/penguins(8).jpeg
  Animals/Penguin/penguins(9).jpeg
Labels: enhancement, hacktoberfest-accepted

#137 Dataset images for Rhinoceros added
  Animals/Rhinoceros/Rhinoceros 1.jpg
  Animals/Rhinoceros/Rhinoceros 10.jpg
  Animals/Rhinoceros/Rhinoceros 11.jpg
  Animals/Rhinoceros/Rhinoceros 2.jpg
  Animals/Rhinoceros/Rhinoceros 3.jpg
  Animals/Rhinoceros/Rhinoceros 4.jpg
  Animals/Rhinoceros/Rhinoceros 5.jpg
  Animals/Rhinoceros/Rhinoceros 6.jpg
  Animals/Rhinoceros/Rhinoceros 7.jpg
  Animals/Rhinoceros/Rhinoceros 8.jpg
  Animals/Rhinoceros/Rhinoceros 9.jpg
Labels: enhancement, hacktoberfest-accepted

#134 added all the necessary images
  potholes dataset/img-1.jpg
  potholes dataset/img-10.jpg
  potholes dataset/img-11.jpg
  potholes dataset/img-12.jpg
  potholes dataset/img-13.jpg
  potholes dataset/img-14.jpg
  potholes dataset/img-15.jpg
  potholes dataset/img-16.jpg
  potholes dataset/img-17.jpg
  potholes dataset/img-18.jpg
  potholes dataset/img-19.jpg
  potholes dataset/img-2.jpg
  potholes dataset/img-20.jpg
  potholes dataset/img-21.jpg
  potholes dataset/img-22.jpg
  potholes dataset/img-23.jpg
  potholes dataset/img-24.jpg
  potholes dataset/img-25.jpg
  potholes dataset/img-26.jpg
  potholes dataset/img-27.jpg
  potholes dataset/img-28.jpg
  potholes dataset/img-29.jpg
  potholes dataset/img-3.jpg
  potholes dataset/img-30.jpg
  potholes dataset/img-31.jpg
  potholes dataset/img-32.jpg
  potholes dataset/img-33.jpg
  potholes dataset/img-34.jpg
  potholes dataset/img-35.jpg
  potholes dataset/img-36.jpg
  potholes dataset/img-37.jpg
  potholes dataset/img-38.jpg
  potholes dataset/img-39.jpg
  potholes dataset/img-4.jpg
  potholes dataset/img-40.jpg
  potholes dataset/img-41.jpg
  potholes dataset/img-42.jpg
  potholes dataset/img-43.jpg
  potholes dataset/img-44.jpg
  potholes dataset/img-45.jpg
  potholes dataset/img-46.jpg
  potholes dataset/img-47.jpg
  potholes dataset/img-48.jpg
  potholes dataset/img-49.jpg
  potholes dataset/img-5.jpg
  potholes dataset/img-50.jpg
  potholes dataset/img-6.jpg
  potholes dataset/img-7.jpg
  potholes dataset/img-8.jpg
  potholes dataset/img-9.jpg
Labels: enhancement, hacktoberfest-accepted

#135 Horse images uploaded
  Animals/Horse/Horse (10).jpg
  Animals/Horse/Horse (11).jpg
  Animals/Horse/Horse (2).jpg
  Animals/Horse/Horse (3).jpg
  Animals/Horse/Horse (4).jpg
  Animals/Horse/Horse (5).jpg
  Animals/Horse/Horse (6).jpg
  Animals/Horse/Horse (7).jpg
  Animals/Horse/Horse (8).jpg
  Animals/Horse/Horse (9).jpg
  Animals/Horse/Horse.jpg
Labels: enhancement, hacktoberfest-accepted

#139 added airplanes
  Transportation/planes/plane-1.jpg
  Transportation/planes/plane-10.jpg
  Transportation/planes/plane-11.jpg
  Transportation/planes/plane-12.jpg
  Transportation/planes/plane-2.jpeg
  Transportation/planes/plane-3.jpg
  Transportation/planes/plane-4.jpg
  Transportation/planes/plane-5.jpg
  Transportation/planes/plane-6.jpg
  Transportation/planes/plane-7.jpg
  Transportation/planes/plane-8.jpg
  Transportation/planes/plane-9.jpg
Labels: enhancement, hacktoberfest-accepted

#140 added rabbit
  Animals/rabbit/Tan-Rabbit.jpg
  Animals/rabbit/rabbit-10.jpg
  Animals/rabbit/rabbit-2.jpg
  Animals/rabbit/rabbit-3.jpg
  Animals/rabbit/rabbit-4.jpg
  Animals/rabbit/rabbit-5.jpg
  Animals/rabbit/rabbit-6.jpg
  Animals/rabbit/rabbit-7.jpg
  Animals/rabbit/rabbit-8.jpg
  Animals/rabbit/rabbit-9.jpg
Labels: documentation, hacktoberfest-accepted

#142 Added a valuable contribution\
  .vs/hacktoberFest/v16/structques.c
Labels: enhancement, hacktoberfest-accepted

#143 Added a gps locator
  gps.py
Labels: enhancement, hacktoberfest-accepted

#144 Added Watermelon dataset
  fruits/Watermelon/Watermelon (10).jpg
  fruits/Watermelon/Watermelon (11).jpg
  fruits/Watermelon/Watermelon (12).jpg
  fruits/Watermelon/Watermelon (13).jpg
  fruits/Watermelon/Watermelon (2).jpg
  fruits/Watermelon/Watermelon (3).jpeg
  fruits/Watermelon/Watermelon (4).jpg
  fruits/Watermelon/Watermelon (5).jpg
  fruits/Watermelon/Watermelon (6).jpg
  fruits/Watermelon/Watermelon (7).jpg
  fruits/Watermelon/Watermelon (8).jpg
  fruits/Watermelon/Watermelon (9).jpg
  fruits/Watermelon/Watermelon.jpeg
Labels: enhancement, hacktoberfest-accepted

#141 Added images of Lion, Cricket, Butterflies, clock and Spinach
  Animals/Lion/1.jpg
  Animals/Lion/10.jpg
  Animals/Lion/2.jpg
  Animals/Lion/3.jpg
  Animals/Lion/4.jpg
  Animals/Lion/5.jpg
  Animals/Lion/6.jpg
  Animals/Lion/7.jpg
  Animals/Lion/8.jpg
  Animals/Lion/9.jpg
  Clock dataset/10.jpg
  Clock dataset/11.jpg
  Clock dataset/12.jpg
  Clock dataset/8.jpg
  Clock dataset/9.jpg
  Cricket/1.jpg
  Cricket/10.jpg
  Cricket/2.jpg
  Cricket/3.jpg
  Cricket/4.jpg
  Cricket/5.jpg
  Cricket/6.jpg
  Cricket/7.jpg
  Cricket/8.jpg
  Cricket/9.jpg
  Vegetables/Spinach/1.jfif
  Vegetables/Spinach/2.jpg
  Vegetables/Spinach/3.jpg
  Vegetables/Spinach/4.jpg
  Vegetables/Spinach/5.jpg
  butterflies/1.webp
  butterflies/10.jpg
  butterflies/2.jpg
  butterflies/3.webp
  butterflies/4.jpeg
  butterflies/5.jpg
  butterflies/6.jpg
  butterflies/7.jpg
  butterflies/8.jpg
  butterflies/9.jpg
Labels: enhancement, hacktoberfest-accepted

#148 Added images of Cartoon
  Cartoon/cartoon1.jpg
  Cartoon/cartoon10.jpg
  Cartoon/cartoon2.jpg
  Cartoon/cartoon3.jpg
  Cartoon/cartoon4.jpg
  Cartoon/cartoon5.jpg
  Cartoon/cartoon6.jpg
  Cartoon/cartoon7.jpg
  Cartoon/cartoon8.jpg
  Cartoon/cartoon9.jpg
Labels: enhancement, hacktoberfest-accepted

#83 tmkoc by aashu singh
  images (1).jpg
  images (2).jpg
  images (3).jpg
  images (5).jpg
  images (6).jpg
  images (7).jpg
  images (9).jpg
  images.jpg
  tmkoc/index.html
Labels: enhancement, hacktoberfest-accepted

#149 Add files via upload
  Animals/Wolf/grey-wolf
Labels: enhancement, hacktoberfest-accepted

#152 Add files via upload
  Animals/doraemon.webp
Labels: enhancement, hacktoberfest-accepted

#154 Added dataset for training
  Animals/bird/sparrow.jpg
Labels: enhancement, hacktoberfest-accepted

#158 Added cheetah images MLproject training.
  Animals/Cheetah/Cheetah-images (1).jpg
  Animals/Cheetah/Cheetah-images (10).jpg
  Animals/Cheetah/Cheetah-images (11).jpg
  Animals/Cheetah/Cheetah-images (12).jpg
  Animals/Cheetah/Cheetah-images (2).jpg
  Animals/Cheetah/Cheetah-images (3).jpg
  Animals/Cheetah/Cheetah-images (4).jpg
  Animals/Cheetah/Cheetah-images (5).jpg
  Animals/Cheetah/Cheetah-images (6).jpg
  Animals/Cheetah/Cheetah-images (7).jpg
  Animals/Cheetah/Cheetah-images (8).jpg
  Animals/Cheetah/Cheetah-images (9).jpg
Labels: enhancement, hacktoberfest-accepted

#157 Deep Learning Project
  Deep Learning project sample - Jupyter Notebook.pdf
Labels: enhancement, hacktoberfest-accepted

#156 Added peacock images to train dataset
  peacock/download (1).jfif
  peacock/download (2).jfif
  peacock/download (3).jfif
  peacock/download (4).jfif
  peacock/download (5).jfif
  peacock/download.jfif
  peacock/images (1).jfif
  peacock/images (2).jfif
  peacock/images (3).jfif
  peacock/images.jfif
Labels: enhancement, hacktoberfest-accepted

#159 Lazy Classifier
  LazyClassifier.pdf
Labels: enhancement, hacktoberfest-accepted

#162 Bear 1,2
  Bear Images/images (3).jpeg
  Bear Images/sloth-bear-20210909-131sb.jpg
Labels: enhancement, hacktoberfest-accepted

#163 Bear 3,4
  Bear Images/aa035d20-a2f1-4268-8410-e3c974091772-Bear_in_Fort_Collins.webp
  Bear Images/images (2).jpeg
Labels: enhancement, hacktoberfest-accepted

#164 Bear 5,6
  Bear Images/images (1).jpeg
Labels: enhancement, hacktoberfest-accepted

#165 Supervised
  Project - unsupervised - Jupyter Notebook.pdf
Labels: enhancement, hacktoberfest-accepted

#168 Dataset images for leopard added
  Animals/Leopard/leopard_1.jpg
  Animals/Leopard/leopard_10.jpg
  Animals/Leopard/leopard_113.jpg
  Animals/Leopard/leopard_2.jpg
  Animals/Leopard/leopard_3.jpg
  Animals/Leopard/leopard_4.jpg
  Animals/Leopard/leopard_5.jpg
  Animals/Leopard/leopard_6.jpg
  Animals/Leopard/leopard_7.jpg
  Animals/Leopard/leopard_8.jpg
  Animals/Leopard/leopard_9.jpg
Labels: enhancement, hacktoberfest-accepted

#170 trash
  images (1).jpg
  images (2).jpg
  images (3).jpg
  images (5).jpg
  images (6).jpg
  images (7).jpg
  images (9).jpg
  images.jpg
Labels: documentation, hacktoberfest-accepted

#171 gora
  Animals/gorilla images/1000_F_157534323_tx4LB9t2mnuVXWJ1zymcQTf8uMVVtPAc.jpg
  Animals/gorilla images/3664779d4b6bd0aa2c3b1e5c30c1b34a.jpg
  Animals/gorilla images/51PB9IHw6VL.jpg
  Animals/gorilla images/PA662HWIC4I6TJTLIBWI6S7HAY.jpg
  Animals/gorilla images/funny-gorilla-drinking-beer-bar-illustration_691560-326.webp
  Animals/gorilla images/gorilla-black.webp
  Animals/gorilla images/istockphoto-1129452040-612x612.jpg
  Animals/gorilla images/maxresdefault.jpg
Labels: enhancement, hacktoberfest-accepted

#172 delete
  tmkoc/index.html
Labels: enhancement, hacktoberfest-accepted

#175 added snakes images
  Animals/snakes/12_-_The_Mystical_King_Cobra_and_Coffee_Forests.jpg
  Animals/snakes/179638.jpg
  Animals/snakes/Bungarus-fasciatus.webp
  Animals/snakes/GettyImages-473994758-15c7a3030ade407486870737cca3f636.jpg
  Animals/snakes/ImageForArticle_21923_16401874858717448.webp
  Animals/snakes/_157b9880-b9e7-11ea-a2a7-d359f39d1b90.jpg
  Animals/snakes/coralsnake.jfif
  Animals/snakes/rattlesnake.jpg
  Animals/snakes/russells_viper.webp
  Animals/snakes/shutterstock-616080827.webp
Labels: enhancement, hacktoberfest-accepted

#176 img bot optimization
  oswald.jpg
Labels: enhancement, hacktoberfest-accepted

#178 added panda images
  Animals/panda/Giant-panda-cub-branch.webp
  Animals/panda/Panda-Bamboo_Panda-Quiz_KIDS_1021_16x9.webp
  Animals/panda/giantpanda-001.jpg
Labels: enhancement, hacktoberfest-accepted

#179 added wolf images
  Animals/Wolf/download (1).jpg
  Animals/Wolf/download.jpg
  Animals/Wolf/unnamed.jpg
Labels: enhancement, hacktoberfest-accepted

#180 added penguin images
  Animals/Penguin/1200px-SGI-2016-South_Georgia_(Fortuna_Bay)–King_penguin_(Aptenodytes_patagonicus)_04.jpg
  Animals/Penguin/1a36b305-412d-405e-a38b-0947ce6709ba.jpeg
  Animals/Penguin/photo-1598439210625-5067c578f3f6.jpg
Labels: enhancement, hacktoberfest-accepted

#181 added parrot images
  Animals/parrot/Indian-Ring-Necked-Parakeet.jpg
  Animals/parrot/maxresdefault.jpg
  Animals/parrot/what-are-green-parrots-called.webp
Labels: enhancement, hacktoberfest-accepted

#177 img bot optimization
  Cartoon/doremon.jpg
Labels: good first issue, hacktoberfest-accepted

#186 Merged Bear, butterflies and peacock images folder to animal folder
  Animals/Bear Images/aa035d20-a2f1-4268-8410-e3c974091772-Bear_in_Fort_Collins.webp
  Animals/Bear Images/images (1).jpeg
  Animals/Bear Images/images (2).jpeg
  Animals/Bear Images/images (3).jpeg
  Animals/Bear Images/index.html
  Animals/Bear Images/sloth-bear-20210909-131sb.jpg
  Animals/butterflies/1.webp
  Animals/butterflies/10.jpg
  Animals/butterflies/2.jpg
  Animals/butterflies/3.webp
  Animals/butterflies/4.jpeg
  Animals/butterflies/5.jpg
  Animals/butterflies/6.jpg
  Animals/butterflies/7.jpg
  Animals/butterflies/8.jpg
  Animals/butterflies/9.jpg
  Animals/peacock/download (1).jfif
  Animals/peacock/download (2).jfif
  Animals/peacock/download (3).jfif
  Animals/peacock/download (4).jfif
  Animals/peacock/download (5).jfif
  Animals/peacock/download.jfif
  Animals/peacock/images (1).jfif
  Animals/peacock/images (2).jfif
  Animals/peacock/images (3).jfif
  Animals/peacock/images.jfif
Labels: documentation, enhancement, hacktoberfest-accepted

#187 House images
  houses/house1.jpg
  houses/house10.jpeg
  houses/house2.jpg
  houses/house3.jpeg
  houses/house4.jpeg
  houses/house5.jpeg
  houses/house6.jpeg
  houses/house7.jpeg
  houses/house8.jpeg
  houses/house9.jpg
Labels: enhancement, hacktoberfest-accepted

#190 koala images added
  Koalas images/k1.jpg
  Koalas images/k10.jpg
  Koalas images/k2.jpg
  Koalas images/k3.jpg
  Koalas images/k4.jpg
  Koalas images/k5.jpg
  Koalas images/k6.jpg
  Koalas images/k7.jpg
  Koalas images/k8.jpg
  Koalas images/k9.jpg
  myqr (1).jpg
  myqr (2).jpg
Labels: enhancement, hacktoberfest-accepted

#194 PDF into audiobook.py
  PDF into audiobook.py
Labels: enhancement, hacktoberfest-accepted

#193 Shell.c
  Shell.c
Labels: enhancement, hacktoberfest-accepted

#192 linear regres
  linear regres
Labels: enhancement, hacktoberfest-accepted

#197 Added Dataset for Training
  Vegetables/Potatoes/images.jpg
Labels: enhancement, hacktoberfest-accepted

#199 Added table Dataset
  Things/Table/photo_2022-10-23_17-09-34.jpg
  Things/Table/photo_2022-10-23_17-09-37.jpg
  Things/Table/photo_2022-10-23_17-09-39.jpg
  Things/Table/photo_2022-10-23_17-09-41.jpg
  Things/Table/photo_2022-10-23_17-09-43.jpg
  Things/Table/photo_2022-10-23_17-09-45.jpg
  Things/Table/photo_2022-10-23_17-09-46.jpg
  Things/Table/photo_2022-10-23_17-09-48.jpg
  Things/Table/photo_2022-10-23_17-09-50.jpg
  Things/Table/photo_2022-10-23_17-09-51.jpg
  Things/Table/photo_2022-10-23_17-09-54.jpg
  Things/Table/photo_2022-10-23_17-10-01.jpg
Labels: enhancement, hacktoberfest-accepted

#195 Laptops Images for ML Training
  1.png
  10.png
  2.png
  3.png
  4.png
  5.png
  6.png
  7.png
  8.png
  9.png
  Laptops/1.png
  Laptops/10.png
  Laptops/2.png
  Laptops/3.png
  Laptops/4.png
  Laptops/5.png
  Laptops/6.png
  Laptops/7.png
  Laptops/8.png
  Laptops/9.png
Labels: enhancement, hacktoberfest-accepted

#201 Add files via upload
  Animals/Panther/1.jpg
  Animals/Panther/10.jpeg
  Animals/Panther/2.jpeg
  Animals/Panther/3.jpeg
  Animals/Panther/4.jpeg
  Animals/Panther/5.jpg
  Animals/Panther/6.jpeg
  Animals/Panther/7.webp
  Animals/Panther/8.jpeg
  Animals/Panther/9.webp
Labels: enhancement, hacktoberfest-accepted

#204 Add files via upload
  Animals/Baboon/1.webp
  Animals/Baboon/10.jpeg
  Animals/Baboon/2.jpeg
  Animals/Baboon/3.jpeg
  Animals/Baboon/4.jpeg
  Animals/Baboon/5.webp
  Animals/Baboon/6.jpeg
  Animals/Baboon/7.jpeg
  Animals/Baboon/8.webp
  Animals/Baboon/9.jpeg
Labels: enhancement, hacktoberfest-accepted

#210 Indian_festivals
  Indian_festivals/1.jpg
  Indian_festivals/10.jpg
  Indian_festivals/11.jpg
  Indian_festivals/2.jpg
  Indian_festivals/3.jpg
  Indian_festivals/4.jpeg
  Indian_festivals/5.jpg
  Indian_festivals/6.jpg
  Indian_festivals/7.jpg
  Indian_festivals/8.jpg
  Indian_festivals/9.jpg
Labels: enhancement, hacktoberfest-accepted

#207 Create sangram.ml
  sangram.ml
Labels: enhancement, hacktoberfest-accepted

#209 Create python4.code
  python4.code
Labels: enhancement, hacktoberfest-accepted

#214 ML Training model
  Drinks-Images/brooke-lark-HjWzkqW1dgI-unsplash.jpg
  Drinks-Images/drew-beamer-bTN-zKFy9uA-unsplash.jpg
  Drinks-Images/edward-howell-jNs7IPdt4HQ-unsplash.jpg
  Drinks-Images/katherine-sousa-ln2R1wJ8TCM-unsplash.jpg
  Drinks-Images/kevin-kelly-PPneSBqfCCU-unsplash.jpg
  Drinks-Images/kobby-mendez-xBFTjrMIC0c-unsplash.jpg
  Drinks-Images/melissa-walker-horn-gtDYwUIr9Vg-unsplash.jpg
  Drinks-Images/michael-discenza-MxfcoxycH_Y-unsplash.jpg
  Drinks-Images/moritz-mentges-Z40sav8IYqQ-unsplash.jpg
  Drinks-Images/readme.md
  Drinks-Images/whitney-wright-TgQkxQc-t_U-unsplash.jpg
Labels: enhancement, hacktoberfest-accepted

#216 Male_Female_Classifier
  Male_Female_Classifier.py
Labels: enhancement, hacktoberfest-accepted

#223 Dataset images for ants
  Animals/Ant/ant.jpeg
  Animals/Ant/images10.jpeg
  Animals/Ant/images6.jpeg
  Animals/Ant/images7.jpeg
  Animals/Ant/images8.jpeg
  Animals/Ant/images9.jpeg
  Animals/Ant/index.jpeg
  Animals/Ant/index2.jpeg
  Animals/Ant/index3.jpeg
  Animals/Ant/index4.jpeg
  Animals/Ant/index5.jpeg
Labels: enhancement, hacktoberfest-accepted

#222 Butterfly
  butterfly/butterfly1.jpg
  butterfly/butterfly10.jpg
  butterfly/butterfly11.jpg
  butterfly/butterfly12.jpg
  butterfly/butterfly2.jpg
  butterfly/butterfly3.jpg
  butterfly/butterfly4.jpg
  butterfly/butterfly5.jpg
  butterfly/butterfly6.jpg
  butterfly/butterfly7.jpg
  butterfly/butterfly8.jpg
  butterfly/butterfly9.jpg
Labels: enhancement, hacktoberfest-accepted

#221 Add files via upload
  Indian Satellites/pic1.jpg
  Indian Satellites/pic10.jpg
  Indian Satellites/pic11.jpg
  Indian Satellites/pic12.jpg
  Indian Satellites/pic2.jpg
  Indian Satellites/pic3.jpg
  Indian Satellites/pic4.jpg
  Indian Satellites/pic5.jpg
  Indian Satellites/pic6.jpg
  Indian Satellites/pic7.jpg
  Indian Satellites/pic8.jpg
  Indian Satellites/pic9.jpg
Labels: enhancement, hacktoberfest-accepted

#219 Added mariegold images for ML training
  flowers/mariegold/download (1).jfif
  flowers/mariegold/download (2).jfif
  flowers/mariegold/download (3).jfif
  flowers/mariegold/download (6).jfif
  flowers/mariegold/download.jfif
  flowers/mariegold/images (1).jfif
  flowers/mariegold/images (2).jfif
  flowers/mariegold/images (3).jfif
  flowers/mariegold/images (4).jfif
  flowers/mariegold/images (5).jfif
  flowers/mariegold/images.jfif
Labels: enhancement, hacktoberfest-accepted

#215 ML Training model using bags images
  Bags-Images/arno-senoner-ZT16YkAYueo-unsplash.jpg
  Bags-Images/aurelia-dubois-xzrJCS4grC4-unsplash.jpg
  Bags-Images/creative-headline-APNnyM36puU-unsplash.jpg
  Bags-Images/diana-light-nvQemFKRBUo-unsplash.jpg
  Bags-Images/he-s-her-lobster-9b6UhV4nLZs-unsplash.jpg
  Bags-Images/irene-kredenets-jKoRZkv2o0U-unsplash.jpg
  Bags-Images/irene-kredenets-pSVYyO-XlJk-unsplash.jpg
  Bags-Images/james-ree-ZmeFtu11Hpc-unsplash.jpg
  Bags-Images/kelly-sikkema-1Pgq9ZpIatI-unsplash.jpg
  Bags-Images/readme.md
  Bags-Images/sun-lingyan-_H0fjILH5Vw-unsplash.jpg
  Bags-Images/wiser-by-the-mile-SwWCo1k92M4-unsplash.jpg
Labels: enhancement, hacktoberfest-accepted

#226 Add files via upload
  Books/book1.jpg
  Books/book10.jpg
  Books/book2.jpg
  Books/book3.jpg
  Books/book4.jpg
  Books/book5.jpg
  Books/book6.jpg
  Books/book7.jpg
  Books/book8.jpg
  Books/book9.jpg
Labels: enhancement, hacktoberfest-accepted

#224 Added hibiscus (flower) images to train dataset.
  flowers/hibiscus/download (1).jfif
  flowers/hibiscus/download (2).jfif
  flowers/hibiscus/download (3).jfif
  flowers/hibiscus/download (4).jfif
  flowers/hibiscus/download (5).jfif
  flowers/hibiscus/download (6).jfif
  flowers/hibiscus/download (7).jfif
  flowers/hibiscus/download.jfif
  flowers/hibiscus/images (1).jfif
  flowers/hibiscus/images (2).jfif
  flowers/hibiscus/images.jfif
Labels: enhancement, hacktoberfest-accepted

#230 Added cartoon photos
  Cartoon/cartoon11.webp
  Cartoon/cartoon12.jpeg
  Cartoon/cartoon13.webp
  Cartoon/cartoon14.webp
  Cartoon/cartoon15.jpg
  Cartoon/cartoon16.avif
Labels: enhancement, hacktoberfest-accepted

#234 removed extra images
  1.png
  10.png
  2.png
  3.png
  4.png
  5.png
  6.png
  7.png
  8.png
  9.png
Labels: enhancement, hacktoberfest-accepted

#232 Create CNN_Gesture.py
  Animals/Cheetah/Cheetah-images (13).jpg
  CNN_Gesture.py
  Confusion_Matrix
Labels: enhancement, hacktoberfest-accepted

#240 Images Added
  Animals/Ant/ant-1.jpg
  Animals/Ant/ant-2.jpg
  Animals/Ant/ant-3.jpg
  Animals/Ant/ant-4.jpeg
  Animals/Ant/ant-5.jpeg
  Animals/Bear Images/bear-1.jpg
  Animals/Bear Images/bear-2.jpg
  Animals/Bear Images/bear-3.jpg
  Animals/Bear Images/bear-4.jpg
  car logo/logo-1.jpg
  car logo/logo-2.jpg
  car logo/logo-4.jpg
  car logo/logo-6.jpg
Labels: enhancement, hacktoberfest-accepted

#238 Add images for Highway idenitifcation
  Highways/Highways-1.jpg
  Highways/Highways-10.jpg
  Highways/Highways-11.jpg
  Highways/Highways-12.jpg
  Highways/Highways-13.jpg
  Highways/Highways-14.jpg
  Highways/Highways-15.jpg
  Highways/Highways-2.jpg
  Highways/Highways-3.jpg
  Highways/Highways-4.jpg
  Highways/Highways-5.jpg
  Highways/Highways-6.jpg
  Highways/Highways-7.jpg
  Highways/Highways-8.jpg
  Highways/Highways-9.jpg
Labels: enhancement, hacktoberfest-accepted

#237 merigold
  flowers/mariegold/merigold 3.jpeg
  flowers/mariegold/merigold 4.jpeg
  flowers/mariegold/merigold.jpeg
  flowers/mariegold/merigold1.jpeg
  flowers/mariegold/merigold2.jpeg
  flowers/mariegold/merigold4.jpeg
  flowers/mariegold/merigold5.jpeg
  flowers/mariegold/merigold6.jpeg
Labels: enhancement, hacktoberfest-accepted
